version: '3'

services:
  rlcraft:
    ports:
      - "25595:25565"
    volumes:
      - /home/yalt/minecraft/rlcraft/data:/data
      - /home/yalt/minecraft/rlcraft/modpacks:/modpacks
    environment:
      EULA: "TRUE"
      MAX_MEMORY: 4G
      VIEW_DISTANCE: 10
      LEVEL_TYPE: LARGEBIOMES
      MAX_PLAYERS: 100
      CONSOLE: "true"
      DIFFICULTY: hard
      VERSION: 1.12.2
      TYPE: FORGE
      FORGEVERSION: 14.23.5.2860
      GENERIC_PACK: /modpacks/RLCraft+Server+Pack+1.12.2+-+Release+v2.9.zip
      GENERIC_PACK_STRIP_DIRS: "1"
      DISABLE_HEALTHCHECK: "false"
    image: itzg/minecraft-server:java8
#    restart: always