version: '3.3'
    
services:

  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - /media/NAS/authelia/:/config #change this to a shared folder on your system. DO NOT use a "volume"
    ports:
      - 9092:9091
    environment:
      - TZ=America/LosAngeles