version: '3.1'
networks:
  loki:
services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - /media/NAS/Mainframe/loki:/etc/loki
    ports:
      - "4100:3100"
    restart: unless-stopped
    networks:
      - loki
  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - /media/NAS/Mainframe/promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    restart: unless-stopped
    networks:
      - loki
  grafana:
    image: grafana/grafana:latest
    user: "1000"
    container_name: grafana
    restart: unless-stopped
    ports:
      - 4000:3000
    volumes:
      - /media/NAS/Mainframe/grafana:/etc/loki
    networks:
      - loki
