version: '2.1'
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1001
      - PGID=1001
      - VIRTUAL_HOST=torrent
      - VIRTUAL_PORT=9091
      - TZ=America/Chicago
    volumes:
      - /opt/docker/volumes/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
      - 9091:9091
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
 
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1001
      - UGID=1001
      - TZ=America/Chicago
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
    volumes:
      - /opt/docker/volumes/transmission/config:/config
      - /mnt/downloads/_Completed:/downloads
    depends_on:
      - wireguard
    network_mode: service:wireguard

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /opt/docker/volumes/nginx-proxy/certs:/etc/nginx/certs
      - /opt/docker/volumes/nginx-proxy/dhparam:/etc/nginx/dhparam
      - /opt/docker/volumes/nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - /opt/docker/volumes/nginx-proxy/conf.d:/etc/nginx/conf.d
      - /opt/docker/volumes/nginx-proxy/html:/usr/share/nginx/html
      - /opt/docker/volumes/nginx-proxy/htpasswd:/etc/nginx/htpasswd
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped