version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/LosAngeles
    volumes:
      - /mnt/HDD/shared/calibre/data/:/config
      - /mnt/HDD/shared/calibre/library:/books
    ports:
      - 8083:8083
    restart: unless-stopped
