version: '3.1'

services:

  db:
    image: postgres
    container_name: postgresdatabase
    restart: unless-stopped
    volumes:
      - /mnt/nas/shared/Network/NUC/postgresdatabase:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: DKZKToPfUjDC5nLmAyvdg3xgD
      PGDATA: /var/lib/postgresql/data/pgdata

  adminer:
    image: adminer
    restart: always
    ports:
      - 6060:8080